### ISSUE TITLE
CRITICAL: Game activity: add alert before try to come back during the game

### ISSUE THREAD

**Issue by inndunas** [Serduk/whatWhereWhen#61]
When button "back" (system or apps) is pressed during the game user shold see pop-up with question "Do you want to leave this game?" (or any similar) and avalaible answers "Yes" and "No". If user choose "Yes" he leaves game and comes to Main Layout, if user choose "No" he comes back to current game.

When button "play" is pressed during the game user shold see pop-up with question "Do you want to leave this game and start new game?" (or any similar) and avalaible answers "Yes" and "No".  If user choose "Yes" he leaves game and comes to Start game pop-up, if user choose "No" he comes back to current game.

**Comment by Serduk** [comment]
Fixed in 0.0.8

After tap on back button -> user see dialog (alert) with 2 buttons Yes and No

After tap on "Yes" -> go to previous screen
After tap on "No" -> stay in game
After tap on black phone behind popup -> dialog close

**Comment by Serduk** [comment]
User Story:
1. User go to game activity
2. User start game
3. User tap on system button back

- Should be displayed dialog window with message ...

If Customer confirm exit -> user should see Main activity
If decline -> should stay on current screen with current game state
if tap on backgorun

**Comment by inndunas** [comment]
@Serduk 
checked in 0.0.9 build.
problem still exists for game button "back", it seems that it shold be fixed together with #57 ?

**Comment by Serduk** [comment]
Should be worked for system button back.

for button back from menu - will be fixed in #57

**Comment by Serduk** [comment]
menu button back fixed in 1.0.0

**Comment by inndunas** [comment]
@Serduk 
checked in 1.0.0
