### ISSUE TITLE
set vertical orientation for Main layout and README

### ISSUE THREAD

**Issue by Serduk** [Serduk/whatWhereWhen#7]
set vertical orientation for Main layout and README

**Comment by Serduk** [comment]
fixed in 8a0095c
0.0.2 and upper build

**Comment by inndunas** [comment]
@Serduk 
horizontal orientation is still exists for Main layout in build 0.0.2

![orientation](https://user-images.githubusercontent.com/38105828/38423734-72bd88f8-39b7-11e8-81f4-56cf8c31c90e.png)

**Comment by Serduk** [comment]
hey, @inndunas 
It will be fixed in 0.0.3 build
Please, check it in that build

**Comment by inndunas** [comment]
@Serduk ,
fix was checked in 0.0.4 build
